### ISSUE TITLE
This project doesn't work for me

### ISSUE THREAD

**Issue by croatiangrn** [jspajic/programsko#1]
Hey @jspajic ,

Can you please tell me what's wrong. I cloned your repo to my computer, tried to execute your app and this is what's bugging me:

Why does your python code show to be running in task manager but the output stops?

Thanks

**Comment by MarioMartic** [comment]
@jspajic I also have same issues as @croatiangrn mentioned. Any help would be appreciated :) Thanks!

**Comment by jspajic** [comment]
Hey guys @croatiangrn @MarioMartic !
Im glad you showed interest for my project.
First make sure you have Python 3+ installed!
